### ISSUE TITLE
Add references

### ISSUE THREAD

**Issue by xiapanqiu** [chenle02/SPDEs-Bib#3]
Math biol references. MR3582808, MR3980910, Etheridge - Some Mathematical Models from Population Genetics

I think this book by Etheridge is better than her another book 'introduction to superprocess'.

Engeneering references. Alan Bain - Dan Crisan - Fundamentals of stochastic filtering, Kallianpur - Stochastic filtering theory

**Comment by chenle02** [comment]
Thanks for suggesting. All of them have been added to the bib.
